{% set version = "0.3.11" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bigutilsr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bigutilsr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bigutilsr/bigutilsr_{{ version }}.tar.gz
  sha256: 3cc7f2c390bbc498a0a156be2595d54a940d1685f1437603378b2b1d58433ef2

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-bigassertr                 # [build_platform != target_platform]
    - r-bigparallelr               # [build_platform != target_platform]
    - r-nabor                      # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - r-rcppeigen                  # [build_platform != target_platform]
    - r-robustbase                 # [build_platform != target_platform]
    - r-rspectra                   # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bigassertr >=0.1.1
    - r-bigparallelr >=0.2.3
    - r-nabor
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppeigen
    - r-robustbase
    - r-rspectra
  run:
    - r-base
    - r-bigassertr >=0.1.1
    - r-bigparallelr >=0.2.3
    - r-nabor
    - r-rcpp
    - r-robustbase
    - r-rspectra

test:
  commands:
    - $R -e "library('bigutilsr')"           # [not win]
    - "\"%R%\" -e \"library('bigutilsr')\""  # [win]

about:
  home: https://github.com/privefl/bigutilsr
  license: GPL-3.0-only
  summary: Utility functions for large-scale data. For now, package 'bigutilsr' mainly includes functions for outlier detection and unbiased PCA projection.
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - pettyalex
